# Generated by Django 2.1 on 2018-09-15 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0005_auto_20180915_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_name',
        ),
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='videofile',
            field=models.FileField(max_length=1000, null=True, upload_to='products/%Y/%m/%d'),
        ),
    ]
