# Generated by Django 2.1 on 2018-10-02 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0008_comment_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='name',
        ),
    ]
